In [1]:
import random

import pandas as pd

# Create a sample dataset
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 35, 28, 22],
    "Department": ["Engineering", "HR", "Engineering", "Marketing", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 45000]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display dataset
print("Full Dataset:")
print(df)

# Task 1: Show employees older than 25
print("\nEmployees older than 25:")
print(df[df["Age"] > 25])

# Task 2: Calculate the average salary
print("\nAverage Salary:")
print(df["Salary"].mean())

# Task 3: Group employees by department and calculate average salary
print("\nAverage Salary by Department:")
print(df.groupby("Department")["Salary"].mean())

# Task 4: Sort employees by salary (highest first)
print("\nEmployees sorted by salary:")
print(df.sort_values(by="Salary", ascending=False))

Full Dataset:
      Name  Age   Department  Salary
0    Alice   25  Engineering   70000
1      Bob   30           HR   50000
2  Charlie   35  Engineering   80000
3    David   28    Marketing   60000
4      Eva   22           HR   45000

Employees older than 25:
      Name  Age   Department  Salary
1      Bob   30           HR   50000
2  Charlie   35  Engineering   80000
3    David   28    Marketing   60000

Average Salary:
61000.0

Average Salary by Department:
Department
Engineering    75000.0
HR             47500.0
Marketing      60000.0
Name: Salary, dtype: float64

Employees sorted by salary:
      Name  Age   Department  Salary
2  Charlie   35  Engineering   80000
0    Alice   25  Engineering   70000
3    David   28    Marketing   60000
1      Bob   30           HR   50000
4      Eva   22           HR   45000

Exploring pandas

In [ ]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

create and import data

In [6]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('organizations-100.csv')

df.head()
#df.shape

(100, 9)

exploring dataframes

In [11]:
import pandas as pd
import random

import warnings
warnings.filterwarnings("ignore")

random.seed(101)

names = ['ngene','sophia', 'liam', 'jennifer']
genders = ['male', 'female', 'male', 'female']
ages = [random.randint(21,25) for _ in range(4)]
marks = [random.randint(1,10) for _ in range(4)]
subjects = random.choices(['python', 'statistics', 'generative AI'], k=4)

df = pd.DataFrame({
    'Name': names ,   # repeat names to match length
    'Gender': genders ,
    'Ages': ages,
    'Marks': marks,
    'Subjects': subjects
})

df

       Name  Gender  Ages  Marks       Subjects
0     ngene    male    25      8     statistics
1    sophia  female    22      1  generative AI
2      liam    male    25      9     statistics
3  jennifer  female    23      4  generative AI

In [14]:
#summary statistics of the dataframe
df.describe().round(2
                    )

        Ages  Marks
count   4.00   4.00
mean   23.75   5.50
std     1.50   3.70
min    22.00   1.00
25%    22.75   3.25
50%    24.00   6.00
75%    25.00   8.25
max    25.00   9.00

In [13]:
df.shape

(4, 5)

In [16]:
df.columns

Index(['Name', 'Gender', 'Ages', 'Marks', 'Subjects'], dtype='str')

selecting and filtering Data

In [18]:
#selecting the 'marks' column

df['Marks']

0    8
1    1
2    9
3    4
Name: Marks, dtype: int64

In [19]:
type(df)

pandas.DataFrame

In [20]:
type(df['Marks'])

pandas.Series

In [24]:
df[["Name", "Marks"]]

       Name  Marks
0     ngene      8
1    sophia      1
2      liam      9
3  jennifer      4

In [25]:
#Filtering rows based on coditions
df[df["Marks"] > 5]

    Name Gender  Ages  Marks    Subjects
0  ngene   male    25      8  statistics
2   liam   male    25      9  statistics

In [26]:
#selecting rows by label based on loc
df.loc[1]

Name               sophia
Gender             female
Ages                   22
Marks                   1
Subjects    generative AI
Name: 1, dtype: object

In [27]:
#selecting rows by index based on iloc
df.iloc[1]

Name               sophia
Gender             female
Ages                   22
Marks                   1
Subjects    generative AI
Name: 1, dtype: object

In [32]:
df.iloc[:1]

    Name Gender  Ages  Marks    Subjects
0  ngene   male    25      8  statistics

In [36]:
#adding column
df['Double_Marks'] = df['Marks'] * 2

df

       Name  Gender  Ages  Marks       Subjects  Double_Marks
0     ngene    male    25      8     statistics            16
1    sophia  female    22      1  generative AI             2
2      liam    male    25      9     statistics            18
3  jennifer  female    23      4  generative AI             8

In [38]:
df['Marks'] = df['Marks'].apply(lambda x: x + 5)

df

       Name  Gender  Ages  Marks       Subjects  Double_Marks
0     ngene    male    25     18     statistics            16
1    sophia  female    22     11  generative AI             2
2      liam    male    25     19     statistics            18
3  jennifer  female    23     14  generative AI             8

In [39]:

df.rename(columns={'Marks' : 'Updated_marks'})

       Name  Gender  Ages  Updated_marks       Subjects  Double_Marks
0     ngene    male    25             18     statistics            16
1    sophia  female    22             11  generative AI             2
2      liam    male    25             19     statistics            18
3  jennifer  female    23             14  generative AI             8

In [42]:
df.drop(["Double_Marks"], axis=1, inplace=True)
df

       Name  Gender  Ages  Marks       Subjects
0     ngene    male    25     18     statistics
1    sophia  female    22     11  generative AI
2      liam    male    25     19     statistics
3  jennifer  female    23     14  generative AI

In [ ]:
#indexing and slicing DataFrames

In [43]:
df['Name']

0       ngene
1      sophia
2        liam
3    jennifer
Name: Name, dtype: str

In [44]:
df['Name'][0]

'ngene'

In [45]:
df[0:2]

     Name  Gender  Ages  Marks       Subjects
0   ngene    male    25     18     statistics
1  sophia  female    22     11  generative AI

In [47]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [48]:
df.columns

Index(['Name', 'Gender', 'Ages', 'Marks', 'Subjects'], dtype='str')

In [50]:
df = df.sort_values(by='Marks', ascending=False)
df

       Name  Gender  Ages  Marks       Subjects
2      liam    male    25     19     statistics
0     ngene    male    25     18     statistics
3  jennifer  female    23     14  generative AI
1    sophia  female    22     11  generative AI

In [54]:
#Merging and Joining Dataframes

df1 = pd.DataFrame({
    'Name': ['A', 'B'],
    'Marks': [25, 30]})

df1

  Name  Marks
0    A     25
1    B     30

In [53]:
df2 = pd.DataFrame({
    'Name': ['A', 'C'],
    'Age' : [44, 32]
})

df2

  Name  Age
0    A   44
1    C   32

In [55]:
#Merging the dataframes on 'Name
pd.merge(df1, df2, on='Name', how='inner')

  Name  Marks  Age
0    A     25   44

In [56]:
pd.merge(df1, df2, on='Name',how='outer')

  Name  Marks   Age
0    A   25.0  44.0
1    B   30.0   NaN
2    C    NaN  32.0