In [33]:
import sqlite3
import pandas as pd

#create an in-memory SQLite database
connection = sqlite3.connect(':memory:')

# Create a cursor object to execute SQL commands
cursor = connection.cursor()

In [3]:
#creating a table

Create_table_query = '''
CREATE TABLE Students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    statistics_marks INTEGER,
    python_marks INTEGER,
    ml_marks INTEGER,
    dl_marks INTEGER
);
'''

cursor.execute(Create_table_query)
print("Table Created")

Table Created

In [4]:
#inserting data into the student table

insert_data_query = '''
INSERT INTO Students (name, age, statistics_marks,python_marks, ml_marks, dl_marks)
VALUES
('Aarav Patel', 20, 85, 90, 88, 92),
('Ayo dele', 21, 70, 60, 90, 92),
('Ngene Emmanuel', 30, 70, 80, 90, 92);

'''

cursor.execute(insert_data_query)
connection.commit()

print('data inserted into students table')

data inserted into students table

In [5]:
#Query the students table and fetch data
query = 'select * from Students'
df = pd.read_sql_query(query, connection)
print("querying the students table")
df

querying the students table

   id            name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1     Aarav Patel   20                85            90        88        92
1   2        Ayo dele   21                70            60        90        92
2   3  Ngene Emmanuel   30                70            80        90        92

In [6]:
#update a record
update_query = "UPDATE Students SET python_marks = 95 WHERE name = 'Ngene Emmanuel'"
cursor.execute(update_query)
connection.commit()

print('updated data from students table')

updated data from students table

In [7]:
#verify the update
updated_df = pd.read_sql_query(query, connection)
updated_df

   id            name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1     Aarav Patel   20                85            90        88        92
1   2        Ayo dele   21                70            60        90        92
2   3  Ngene Emmanuel   30                70            95        90        92

In [ ]:
#close the connections when done

connection.close()
cursor.close()

**CONNECTING MySQL Database to PYTHON**

In [34]:
import pymysql




# Establish a connection
connection = pymysql.connect(
    host=host,
    port=port,
    user=user,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor
)

print("connected to database")

connected to database

In [35]:
Create_table_query = '''
CREATE TABLE Students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    statistics_marks INT,
    python_marks INT,
    ml_marks INT,
    dl_marks INT
);
'''
cursor.execute(Create_table_query)
print("Table Created")

Table Created

In [36]:
insert_data_query = '''
INSERT INTO Students (name, age, statistics_marks, python_marks, ml_marks, dl_marks)
VALUES
('Aarav Patel', 20, 85, 90, 88, 92),
('Ayo Dele', 21, 70, 60, 90, 92),
('emmy codes', 22, 78, 50, 98, 72),
('sandra benede', 25, 73, 40, 80, 32),
('Ngene Emmanuel', 30, 70, 80, 90, 92);

'''
cursor.execute(insert_data_query)
connection.commit()

print("Data inserted into Students table")

Data inserted into Students table

In [7]:
# Create a cursor
cursor = connection.cursor()

cursor.execute("select * from Students LIMIT 5")

rows = cursor.fetchall()
for row in rows:
    print(row)

cursor.close()
connection.close()

{'id': 1, 'name': 'Aarav Patel', 'age': 20, 'statistics_marks': 85, 'python_marks': 90, 'ml_marks': 88, 'dl_marks': 92}
{'id': 2, 'name': 'Ayo Dele', 'age': 21, 'statistics_marks': 70, 'python_marks': 60, 'ml_marks': 90, 'dl_marks': 92}
{'id': 3, 'name': 'Ngene Emmanuel', 'age': 30, 'statistics_marks': 70, 'python_marks': 80, 'ml_marks': 90, 'dl_marks': 92}
{'id': 4, 'name': 'Aarav Patel', 'age': 20, 'statistics_marks': 85, 'python_marks': 90, 'ml_marks': 88, 'dl_marks': 92}
{'id': 5, 'name': 'Ayo Dele', 'age': 21, 'statistics_marks': 70, 'python_marks': 60, 'ml_marks': 90, 'dl_marks': 92}

Using MySQL Connected in Python

In [18]:
import mysql.connector
from mysql.connector import Error

try:
    connection = mysql.connector.connect(
        host=host,
        port=port,
        user=user,
        password=password,
        database=database

    )
    if connection.is_connected():
        print("connected to database")

except mysql.connector.Error as error:
    print('Failed to connect to database', error)

connected to database

In [19]:
#Create a cursor
cursor = connection.cursor()



cursor.execute('SELECT * FROM Students LIMIT 5')

rows = cursor.fetchall()
for row in rows:
    print(row)

(1, 'Aarav Patel', 20, 85, 90, 88, 92)
(2, 'Ayo Dele', 21, 70, 60, 90, 92)
(3, 'Ngene Emmanuel', 30, 70, 80, 90, 92)
(4, 'Aarav Patel', 20, 85, 90, 88, 92)
(5, 'Ayo Dele', 21, 70, 60, 90, 92)

In [16]:
#Close database connection
if 'connection' in locals() and connection.is_connected():
    cursor.close()
    connection.close()
    print('mySQL connection is closed')

mySQL connection is closed

# **1.Connecting Pandas with MySQL Database**

In [38]:
import pandas as pd
from sqlalchemy import create_engine

#Create a connection string

# Encode the password safely, not really needed, i did it because @ in my password was been misinterpreted as the beginning of the host
from urllib.parse import quote_plus
import pandas as pd
from sqlalchemy import create_engine
password = quote_plus("Edge@2020")

connection_string = f'mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}'
print(connection_string)


#create an SQLAlchemy
engine = create_engine(connection_string)

mysql+mysqlconnector://admin:Edge%402020@127.0.0.1:3306/ai_agent_db

In [39]:
query = "SELECT * FROM Students"
df = pd.read_sql(query, con=engine)
df

   id            name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1     Aarav Patel   20                85            90        88        92
1   2        Ayo Dele   21                70            60        90        92
2   3  Ngene Emmanuel   30                70            80        90        92
3   4     Aarav Patel   20                85            90        88        92
4   5        Ayo Dele   21                70            60        90        92
5   6      emmy codes   22                78            50        98        72
6   7   sandra benede   25                73            40        80        32
7   8  Ngene Emmanuel   30                70            80        90        92

**2. filter record based on conditions**

In [40]:
query = " SELECT * FROM Students WHERE python_marks > 85"
df = pd.read_sql(query, con=engine)
df

   id         name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1  Aarav Patel   20                85            90        88        92
1   4  Aarav Patel   20                85            90        88        92

**3. Select specific columns**

In [43]:
query = "SELECT name, statistics_marks FROM Students "
df = pd.read_sql(query, con=engine)
df

             name  statistics_marks
0     Aarav Patel                85
1        Ayo Dele                70
2  Ngene Emmanuel                70
3     Aarav Patel                85
4        Ayo Dele                70
5      emmy codes                78
6   sandra benede                73
7  Ngene Emmanuel                70

**4.ORDER RECORDS BY A SPECIFIC COLUMN (e.g, order by ml_marks in descending order)**

In [44]:
query = "SELECT * FROM Students ORDER BY ml_marks DESC"
df = pd.read_sql(query, con=engine)
df

   id            name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   6      emmy codes   22                78            50        98        72
1   2        Ayo Dele   21                70            60        90        92
2   3  Ngene Emmanuel   30                70            80        90        92
3   5        Ayo Dele   21                70            60        90        92
4   8  Ngene Emmanuel   30                70            80        90        92
5   1     Aarav Patel   20                85            90        88        92
6   4     Aarav Patel   20                85            90        88        92
7   7   sandra benede   25                73            40        80        32

**5. Aggregate functions(e.g average marks in statistics**

In [45]:
query = "SELECT AVG(statistics_marks) AS avg_statistics_marks FROM Students"
df = pd.read_sql(query, con=engine)
df

   avg_statistics_marks
0                75.125

**6. Count the no. of students**

In [47]:
query = "SELECT count(*) AS total_students FROM Students"
df = pd.read_sql(query, con=engine)
df

   total_students
0               8

**7.Group by (e.g, average marks grouped by age)**

In [48]:
query = "select age, AVG(statistics_marks) as avg_statistics_marks FROM Students GROUP BY age"
df = pd.read_sql(query, con=engine)
df

   age  avg_statistics_marks
0   20                  85.0
1   21                  70.0
2   30                  70.0
3   22                  78.0
4   25                  73.0

**8.closing SQLAlchemy connections, ost times it is closed automatically except when used by multiple users**

In [ ]:
engine.dispose()

# **_PostgresDB Connection using Python_**