In [2]:
import sqlite3
import pandas as pd

#create an in-memory SQLite database
connection = sqlite3.connect(':memory:')

# Create a cursor object to execute SQL commands
cursor = connection.cursor()

In [3]:
#creating a table

Create_table_query = '''
CREATE TABLE Students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    statistics_marks INTEGER,
    python_marks INTEGER,
    ml_marks INTEGER,
    dl_marks INTEGER
);
'''

cursor.execute(Create_table_query)
print("Table Created")

Table Created

In [4]:
#inserting data into the student table

insert_data_query = '''
INSERT INTO Students (name, age, statistics_marks,python_marks, ml_marks, dl_marks)
VALUES
('Aarav Patel', 20, 85, 90, 88, 92),
('Ayo dele', 21, 70, 60, 90, 92),
('Ngene Emmanuel', 30, 70, 80, 90, 92);

'''

cursor.execute(insert_data_query)
connection.commit()

print('data inserted into students table')

data inserted into students table

In [5]:
#Query the students table and fetch data
query = 'select * from Students'
df = pd.read_sql_query(query, connection)
print("querying the students table")
df

querying the students table

   id            name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1     Aarav Patel   20                85            90        88        92
1   2        Ayo dele   21                70            60        90        92
2   3  Ngene Emmanuel   30                70            80        90        92

In [6]:
#update a record
update_query = "UPDATE Students SET python_marks = 95 WHERE name = 'Ngene Emmanuel'"
cursor.execute(update_query)
connection.commit()

print('updated data from students table')

updated data from students table

In [7]:
#verify the update
updated_df = pd.read_sql_query(query, connection)
updated_df

   id            name  age  statistics_marks  python_marks  ml_marks  dl_marks
0   1     Aarav Patel   20                85            90        88        92
1   2        Ayo dele   21                70            60        90        92
2   3  Ngene Emmanuel   30                70            95        90        92

In [ ]:
#close the connections when done

connection.close()
cursor.close()


CONNECTING MySQL Database to PYTHON

In [ ]:
import pymysql

#database configuration

host = ''